### PR TITLE
Simple script to create a top-level map-annotation from a study tsv file

### PR DESCRIPTION
**Pull request by manics**
Example (current working dir: `idr-metadata/`):

```
export PYTHONPATH=.:~/OMERO.server/lib/python
scripts/annotate_study.py \
    idr-metadata/idr0001-graml-sysgro/idr0001-study.txt Screen:3
```

This will automatically prompt for a login if there is no current CLI session (from `omero login`)

### CODE REVIEW

**Comment by manics** [comment]
I've added `pyidr.mapannotations.create_map_annotation` because https://github.com/openmicroscopy/openmicroscopy/pull/4786 changes `BulkToMapAnnotationContext`.

**Comment by joshmoore** [comment]
Not merging for 0.2.1 or 0.3.0-rc1.

**Comment by aleksandra-tarkowska** [comment]
--exclude

**Comment by aleksandra-tarkowska** [comment]
--exclude

**Comment by aleksandra-tarkowska** [comment]
--exclude

**Pull request closed without merging**
