### PR TITLE
check_screen: output file count

### PR DESCRIPTION
**Pull request by simleo**
Adds a final file count to the output of `scripts/check_screen.py`. Also, error messages are now printed to stderr only in verbose mode.

### CODE REVIEW

**Comment by joshmoore** [comment]
Closing & re-opening now that I've re-enabled travis (after the move between orgs)

**Comment by simleo** [comment]
Re: build failure see #67

**Comment by joshmoore** [comment]
Trying a close/re-open again.

**Comment by joshmoore** [comment]
Green

**Pull request merged**
