### PR TITLE
idr0035: .screen files

### PR DESCRIPTION
**Pull request by simleo**
Adds .screen files for idr0035, together with the code used to generate them.

```
[simleo:screenA] (idr0035_screens) % awk '{print $2}' idr0035-screenA-plates.tsv | while read f; do python ../../scripts/check_screen.py -ev "${f}"; done | grep ^files | uniq -c
     55 files: 720 (missing: 0)
```

### CODE REVIEW

**Comment by manics** [comment]
Can you also add your download script `bbbc_img_links.py` to this directory? I know you said it should be generic, but if it's modified in future it's not going to be retested against older downloads.

**Comment by eleanorwilliams** [comment]
I don't understand how the script knows which file is from each channel, but comparing to the BBBC021_v1_image.csv file from https://data.broadinstitute.org/bbbc/BBBC021/ it looks like in some fields the channels files might be in the wrong order. 

Eg. in the Week10_40111.screen file - looking at well B02 (= Well 13) where I think the order of files should be DAPI,Tubulin,Actin for field 1 the .screen file has 
Week10_200907_B02_s2_w<273BF3441-EEC5-4D6C-826D-15B81FAC24D9,4E95A4CD8-0BCD-4113-9963-23C5842CDDE8,1CD1D8755-B3D7-4FD9-B53D-E02135CA94F0>.tif
but in the .csv it has 
Image_FileName_DAPI = Week10_200907_B02_s2_w1CD1D8755-B3D7-4FD9-B53D-E02135CA94F0.tif
Image_FileName_Tubulin = Week10_200907_B02_s2_w273BF3441-EEC5-4D6C-826D-15B81FAC24D9.tif
Image_FileName_Actin = Week10_200907_B02_s2_w4E95A4CD8-0BCD-4113-9963-23C5842CDDE8.tif
which is different to the order in the .screen file. 
Looks the same for s3 but s0 and s2 look correct.

**Comment by simleo** [comment]
According to `BBBC021_v1_image.csv` (one of the metadata files in the dataset), the association is:

```
w1 -> DAPI
w2 -> Tubulin
w4 -> Actin
```

More explicitly, you can run this on `BBBC021_v1_image.csv` with no errors:

```python
import csv
import re

CHANNEL_PATTERN = re.compile(r"(.+)_w(.+)\.tif")

def getch(name):
    return CHANNEL_PATTERN.match(name).groups()[1]

with open("BBBC021_v1_image.csv") as f:
    reader = csv.DictReader(f)
    for i, r in enumerate(reader):
        assert getch(r["Image_FileName_DAPI"]).startswith("1")
        assert getch(r["Image_FileName_Tubulin"]).startswith("2")
        assert getch(r["Image_FileName_Actin"]).startswith("4")
```

So my idea was to define `CHANNEL_NAMES = "DAPI", "Tubulin", "Actin"` for all wells and fields and then sort the channel strings so that they always match correctly, but I actually forgot to sort. Fixed in 4a889f7.

**Comment by eleanorwilliams** [comment]
@simleo - the .screen files look correct now. Thanks.

**Comment by eleanorwilliams** [comment]
@simleo - I have imported the images into idr0035 on test43 (which is idr-testing.openmicroscopy.org) and they look fine except the channel names appear as 'DAPI', '1','2'.  I can't see why they wouldn't all have the names specified in the .screen files.  Any ideas?

**Pull request merged**
