### PR TITLE
Idr0035

### PR DESCRIPTION
**Pull request by eleanorwilliams**
Initial commits, will need more. 
Note: the plates.tsv file is in https://github.com/IDR/idr-metadata/pull/255/

Will be tested in test43

### CODE REVIEW

**Comment by eleanorwilliams** [comment]
This will not go into the 0.4.3 release of IDR. Do not merge yet.

**Comment by eleanorwilliams** [comment]
Ready for testing on test44.

**Comment by joshmoore** [comment]
@eleanorwilliams : how do you see this moving forward?

**Comment by eleanorwilliams** [comment]
@joshmoore. Testing of annotations in test44 went fine.  All looks ok to me.  Only outstanding question is what to do in the cases where the channels are not being named correctly (https://github.com/IDR/idr-metadata/pull/255) and do we want to create a renderdef.yml to change the max and min.  Do we need to talk to @sbesson to see if there is someone who could look at the channel name issue?  Then I could see if there is a rendering setting that looks decent for the max and min.

**Comment by joshmoore** [comment]
Discussed today: @eleanorwilliams trying her hand at a render yml file, but all agree that this points to a deeper issue needing investigation.

**Comment by eleanorwilliams** [comment]
@joshmoore.  I have now removed the renderdef.yml file as this does not fix the channel problem.  Fix will come from Bioformats.  

Annotations will not be changed so this PR could be merged for prod44 if we think it will go in that release.

**Pull request merged**
