### PR TITLE
parallel-based re-annotation scripts

### PR DESCRIPTION
**Pull request by joshmoore**
These may not be significant enough for inclusion in the repository
but are an example of how the EBI demo3 server was created.

### CODE REVIEW

**Comment by manics** [comment]
FYI there's some old mini-IDR scripts which automatically query the db for screen names and figures out the idr-metadata https://github.com/IDR/idr-metadata/blob/master/scripts/mini/idr-setup-3.sh

**Comment by joshmoore** [comment]
@manics: definitely like the idea of scripting the screen/project input list, but since this is the state I've tested, merging for 0.3.0-rc1 and we can certainly look to combine with mini-idr moving forward.

**Comment by aleksandra-tarkowska** [comment]
all works great, just minor comments:

- some csv fiels are gziped, they first needs to be unzipped

```
find . -name '*.csv.gz' -exec gzip -d {} \;
```

**Comment by joshmoore** [comment]
Were you having issues with the gzipped files? populate_metadata has support internally: https://github.com/openmicroscopy/openmicroscopy/pull/4754/files#diff-32b25f7075b9602021940173873c7224R766

**Comment by aleksandra-tarkowska** [comment]
looks like that is no longer working, see mitochek

**Pull request merged**
