### PR TITLE
updated screen description

### PR DESCRIPTION
**Pull request by eleanorwilliams**
minor edit to screen description after text change by Davide Danovi, probably fine to merge.

### CODE REVIEW

**Comment by joshmoore** [comment]
@eleanorwilliams : ready to merge?

**Comment by joshmoore** [comment]
Merging for release. (Present on prod37)

**Comment by eleanorwilliams** [comment]
Don't merge yet - thought that we should add an "Example" image to the study file

**Comment by joshmoore** [comment]
Too late. We'll need to have a last PR for that then.

**Comment by eleanorwilliams** [comment]
OK.  Let leave the example images for now and we'll have a PR for 0.3.8 which will include the pubmed ID, DOI etc for the publication too.

**Pull request merged**
