### PR TITLE
Add find_pattern_2seq

### PR DESCRIPTION
**Pull request by simleo**
Adds a function that compares two sequences and extracts a file pattern string that describes them, but see the FIXME note in the docstring for a caveat.

### CODE REVIEW

**Comment by joshmoore** [comment]
What's the driver for this? Could it change the representation of some (existing) data?

**Comment by simleo** [comment]
Yes, but not necessarily for the best :) As we have discussed, *fully automated* pattern detection is unreliable. Thus, the intended usage for something like this is to aid in the creation of .screen files. For instance:

```python
>>> import os
>>> import glob
>>> import pyidr.file_pattern as fp
>>> os.chdir("TARA_HCS1_H5_G100008152_G100008154--2013_11_04_20_31_35/slide--S00/chamber--U01--V01")
>>> filenames = glob.glob("*/*.tif")
>>> len(filenames)
39600
>>> fp.find_pattern_2seq(min(filenames), max(filenames))
'field--X<00,17>--Y<00,21>/image--L00--S00--U01--V01--J08--E00--O0<2,0>--X<00,17>--Y<00,21>--T00--Z<00,19>--C0<0,4>.ome.tif'
```

This is not the final set of patterns, but it gives a good idea of how the files are structured and it's faster than visual inspection. It's a rudimentary tool, but it could be made better.

**Comment by joshmoore** [comment]
Here's definitely a driver: https://trello.com/c/vpc8NKAC/163-idr-metamorph-stk-per-channel

Currently testing via:

```
#!/usr/bin/env python
from pyidr import file_pattern as fp
from glob import glob
base = "/uod/idr/filesets/idr0010-doil-dnadamage/20150501-original/Restored GW screen/"
dirs = glob(base + "/*")

def iglob(pattern):
  def either(c):
    return '[%s%s]'%(c.lower(),c.upper()) if c.isalpha() else c
  return glob(''.join(map(either,pattern)))


for dir in dirs:
  try:
    dapi, = [x for x in iglob(dir + "/*dapi*") if "spot" not in x]
    try:
      bp, = [x for x in iglob(dir + "/*bp*") if "spot" not in x]
    except: # Try BB
      bp, = [x for x in iglob(dir + "/*bb*") if "spot" not in x]
  except:
    raise Exception(dir)
  print fp.find_pattern_2seq(dapi, bp)
```

The matching `p` in the two channel names ("dapi" and "bp") leads to:

```
.../62-01/62 <da,53b>p<i,1>.stk
```

**Comment by joshmoore** [comment]
With a small hack:

```
  bp = bp.replace("bp", "bxxx")
  rv = fp.find_pattern_2seq(dapi, bp)
  rv = rv.replace("bxxx", "bp")
```

I can get quite resonable results. Moving discussion to the card. From my point of view, this can be merged and worked on further later.

**Comment by joshmoore** [comment]
Merging for 0.0.4 then.

**Pull request merged**
