### PR TITLE
Decouple idr0033 metadata files into a submodule

### PR DESCRIPTION
**Pull request by sbesson**
As additional enrichment work is likely to be done on this study, this is the occasion to split it into its own repository

see: https://github.com/IDR/idr0089-fischl-coldtemp

### CODE REVIEW

**Review by joshmoore — APPROVED** [review]
Looks generally fine to me. On the separated repo, I'd vote for:

 - a README at least like https://github.com/IDR/idr0021-lawo-pericentriolarmaterial if not generated from the study file ;) (copyright would be good)
 - a description, potentially with a link to to the study?
 - use of the [topic](https://github.com/search?q=topic%3Aidr+org%3AIDR&type=Repositories)

Though all of those vary across the study repos so no blocker here.

**Comment by sbesson** [comment]
As expected, the main impact here will be the invalidation of the memo files due to the timestamps. Given the study is only 8 plates big, that's a cost we can easily take on board for `prod89`. Computing the regeneration time as we speak.

**Comment by sbesson** [comment]
For reference

```
[sbesson@pilot-idr0094-omeroreadwrite idr0033-rohban-pathways]$ tail -F /opt/omero/server/OMERO.server/var/log/Blitz-0.log | grep memo
2020-10-01 10:40:19,006 DEBUG [                   loci.formats.Memoizer] (erver-5536) memo(lastModified=1565757103000) older than real(lastModified=1601548792000)
2020-10-01 11:01:49,856 DEBUG [                   loci.formats.Memoizer] (erver-5536) saved to temp file: /data/OMERO/BioFormatsCache/data/OMERO/ManagedRepository/demo_2/2017-03/06/14-24-32.180/data/idr-metadata/idr0033-rohban-pathways/screens/.41744.screen.bfmemo508584875777910616
2020-10-01 11:01:49,918 DEBUG [                   loci.formats.Memoizer] (erver-5536) saved memo file: /data/OMERO/BioFormatsCache/data/OMERO/ManagedRepository/demo_2/2017-03/06/14-24-32.180/data/idr-metadata/idr0033-rohban-pathways/screens/.41744.screen.bfmemo (9557058 bytes)
```

**Comment by joshmoore** [comment]
But of course, if need be we could fake the time stamps. I remember doing that previously.

**Comment by manics** [comment]
I thought git filter would keep the original author timestamps anyway? (Used by https://github.com/IDR/idr-utils/blob/687b2147cd7631307694f6329ed2251b56a45ee0/scripts/git-restore-mtime-bare.py#L50).

**Comment by manics** [comment]
Just realised the above script doesn't recurse into submodules. Maybe we need to fix that.

**Comment by sbesson** [comment]
Edit: running `sudo python idr-utils/scripts/git-restore-mtime-bare.py` was actually sufficient for fixing the timestamps and loading the memo files without invalidation.

**Comment by sbesson** [comment]
> Just realised the above script doesn't recurse into submodules. Maybe we need to fix that.

Interestingly enough the command above worked probably since the files are still in Git history.

Despite the absence of submodule, it looks like recent clones of `idr-metadata` restore the author timestamps for screen files in decoupled repositories

```
[sbesson@pilot-idr0094-omeroreadwrite metadata]$ ls -alh idr0064-goglia-erkdynamics/screens/
total 116K
drwxr-xr-x. 2 omero-server idrnfs 4.0K Apr 23 13:37 .
drwxr-xr-x. 6 omero-server idrnfs 4.0K Apr 28 07:58 ..
-rw-r--r--. 1 omero-server idrnfs 9.2K Apr 23 13:37 1.1.screen
-rw-r--r--. 1 omero-server idrnfs 9.2K Apr 23 13:37 1.2.screen
-rw-r--r--. 1 omero-server idrnfs 9.2K Apr 23 13:37 1.3.screen
-rw-r--r--. 1 omero-server idrnfs 9.2K Apr 23 13:37 2.1.screen
-rw-r--r--. 1 omero-server idrnfs 9.2K Apr 23 13:37 2.2.screen
-rw-r--r--. 1 omero-server idrnfs 9.2K Apr 23 13:37 2.3.screen
-rw-r--r--. 1 omero-server idrnfs 9.2K Apr 23 13:37 3.1.screen
-rw-r--r--. 1 omero-server idrnfs 9.2K Apr 23 13:37 3.2.screen
-rw-r--r--. 1 omero-server idrnfs 9.2K Apr 23 13:37 3.3.screen
```

**Comment by sbesson** [comment]
Thanks all. Merging and deploying on `prod89`. I will capture the restore time script todo as an issue. Re https://github.com/IDR/idr-metadata/pull/449 agreed. For scalability, my current ideal scenario would be to generate these README from the study files via the study_parser and set up a GitHub action to keep the README up-to-date. I'll also capture this as an issue (or try it out next week).

**Pull request merged**
