### PR TITLE
New mapr bulk

### PR DESCRIPTION
**Pull request by aleksandra-tarkowska**
mapr branch should be reset to 

```
*   121e41f (origin/master, origin/HEAD) Merge pull request #161 from joshmoore/fix-pandas
```

### CODE REVIEW

**Comment by eleanorwilliams** [comment]
All bulkmap config files checked including those with organsim group. 
For idr0020-A there is no 'siRNA identifier', just an 'siRNA Pool Identifier' - will it cause a problem having siRNA Identifier as a primary key?

**Comment by aleksandra-tarkowska** [comment]
@eleanorwilliams 20 fixed now, sorry my mistake

**Comment by joshmoore** [comment]
Currently testing on `josh3-*`

**Comment by eleanorwilliams** [comment]
Looking at some of the gene annotations I think its really confusing that information that is gene related but specific to a particular screen gets pulled together.  

e.g. http://10.0.51.193/webclient/?show=image-179774 has information about what gene annotation builds were used to assign the siRNA to the gene in all screens, where we just want to see the one related to the screen we are looking at.  I don't think this information should be separated from gene though, it is related to the gene.

Similarly http://10.0.51.193/webclient/?show=image-1824050 shows information about ORFs linked to the tagged protein even though the well is from an siRNA screen.  The ORF information is again related to the gene and it would be shame to have this hidden away in the 'other' section.

So solution is to put most if not all of the information about siRNAs and genes into the relevant primary key sections in the yaml files.

**Comment by eleanorwilliams** [comment]
Other option that Simon mentioned in a chat today is have screen specific gene/siRNA/compound info in another group than other like a screen-gene group.

**Comment by joshmoore** [comment]
Thoughts on getting this in for 0.3.0-rc1 before we start a restructuring?

**Comment by eleanorwilliams** [comment]
Do-able if we decide how to do it - add more to primary keys or create additional groups.

**Comment by joshmoore** [comment]
https://github.com/IDR/idr-metadata/pull/162/commits/18690807a50a1f7973b5e0374dbf3216f6691323 was the last tested state on the demo3 system. Merging this PR as is for 0.3.0-rc1 even though the last few commits may need further work.

**Pull request merged**
