### PR TITLE
Example walkthrough for calculating features

### PR DESCRIPTION
**Pull request by manics**
Use the `idr0013-neumann-mitocheck/screenA` feature calculation as an example.

Currently incomplete because the image names don't match the filenames, so the script for converting avro to OMERO.features needs modification to use another mapping file.

### CODE REVIEW

**Comment by joshmoore** [comment]
Are the playbooks that you used to set up the current cluster somewhere or was it done manually?

**Comment by manics** [comment]
https://github.com/openmicroscopy/infrastructure/pull/257 and the corresponding private group_vars. The only manual step was `docker run ... redis ...`.

**Comment by manics** [comment]
Related:
- https://github.com/openmicroscopy/pydoop-features/pull/48
- https://github.com/openmicroscopy/pydoop-features/pull/49

**Comment by manics** [comment]
Another possibility is to move this to https://github.com/IDR/idr-metadata/pull/239 and have a full walkthrough/script for each feature calculation run.

**Comment by joshmoore** [comment]
Thanks for the README. I'll follow this when trying to collate the now complete mito/screenB and cellmorph runs. @simleo : I'll probably contact you about the condensation calculation step. Whether or not this gets combined with the re-organization from gh-239 will take place on that PR.

**Pull request merged**
