### PR TITLE
first pass at files for idr0026-A

### PR DESCRIPTION
**Pull request by eleanorwilliams**
Not ready for merging yet.  First pass at files.  Need ontology terms adding and still needs bulkmap-config file and annotation.csv.

### CODE REVIEW

**Comment by eleanorwilliams** [comment]
@joshmoore.  This is ready for image loading testing, but it will be worth you looking over the filePaths.tsv file first to see if you think the file paths for the mixture of .pattern files for the raw images and .tifs for the processed images will work.  I took the .pattern file paths from Simone's file in https://github.com/IDR/idr-metadata/pull/213

**Comment by joshmoore** [comment]
Do you want to delete your tsv file in favor of @simleo's? (gh-213)

Excluding for the moment.

--exclude

**Comment by eleanorwilliams** [comment]
We could use @simleo's filepaths.tsv for a first try of the pattern files but his doesn't include the processed image files and it has a different dataset for each directory, whereas in some cases for the same mouse tumor the timelapse had to be restarted so we want the images from more than one directory to be part of the same dataset.

**Comment by joshmoore** [comment]
Ok to close?

**Comment by simleo** [comment]
@joshmoore Yes, fully cherry-picked into #213

**Pull request closed without merging**
