### PR TITLE
Python 3 scripts upgrades

### PR DESCRIPTION
**Pull request by sbesson**
Replaces #404 

- upgrades `.travis.yml` to run on `xenial/Python3` by default
- bumps `idr-utils` to the latest version including Python 3 support
- bumps all study submodules with Python3 script upgrades
- fixes the remaining scripts in this repository to be Python 3 compatible

Expecting Travis CI green should be sufficient to validate this. Once merged, this should make this repository compatible with Python 3 environments which are now the default in IDR.

/cc @dominikl @manics @joshmoore

### CODE REVIEW

**Comment by jburel** [comment]
Changes make sense and travis is green 
in other repos e.g. figure we explicitly set the Python version to 3.6 see https://github.com/ome/omero-figure/blob/master/.travis.yml

**Comment by sbesson** [comment]
So do you suggest adding an explicit Python version for unification?

**Comment by jburel** [comment]
yes. Since we have not yet tested other Python version

**Comment by sbesson** [comment]
> yes. Since we have not yet tested other Python version

:+1: pushed ab98b5e to pin the Python version

**Comment by dominikl** [comment]
Looks good from my point of view 👍

**Comment by sbesson** [comment]
@jburel ping re https://github.com/IDR/idr-metadata/pull/405#event-3178600482

**Pull request merged**
