### PR TITLE
idr0016 update

### PR DESCRIPTION
**Pull request by simleo**
Adds `.screen` files for 58 new plates.

**NOTE:** I have sorted the `*plates.tsv` file after generating it in order to minimize the diff.

### CODE REVIEW

**Comment by eleanorwilliams** [comment]
@simleo, I really can't comment on the code changes but it looks like the correct files are added.  I'm not sure what we should do with the .screen files for the plates in 2016-01-19-screens-bbbc022.  Maybe its I ok that we show they were created here and then I could maybe copy them to the idr0036 directories.  What do you think?

**Comment by eleanorwilliams** [comment]
@simleo I have created a symbolic link for the BBBC022 files to /uod/idr/filesets/idr0036-gustafsdottir-cellpainting/2016-01-19-screens-bbbc022 and I will ask Josh if we can actually move them here.  The plates.tsv file for idr0016 should NOT contain the 20 plates in BBBC022 and the .screen files for them should not be in this PR.    Ideally the .screen generation file would take the location of the files as input and would be at a higher level, meaning that we could generate the .screen files for the idr0016 and idr0036/BBBC022 images separately.

**Comment by simleo** [comment]
@eleanorwilliams I have moved the code to `scripts/gen_screens_0016_0036`, generated `.screen` files for idr0036 and updated idr0016 according to the removal of BBBC022. I have **not** committed the plates file for idr0036 to avoid conflicts with #259 (it's the same).

**Comment by eleanorwilliams** [comment]
@simleo This all looks correct to me.

**Comment by joshmoore** [comment]
Merging for `0.4.3-1`

**Pull request merged**
