### PR TITLE
Single branch all updated annotations

### PR DESCRIPTION
**Pull request by eleanorwilliams**
This branch has updated annotations for all screens under
idr0001, idr0002, idr0003, idr0004, idr0005, idr0006, idr0007, idr0008, idr0009, idr0010, idr0013, idr0016, idr0017, idr00018, idr0019, idr0020, idr0021.

plus idr0012-screenA only (not screens B and C)

idr0023 not included yet.

### CODE REVIEW

**Comment by manics** [comment]
Proposed changes for mapr in https://github.com/eleanorwilliams/idr-metadata/pull/19

**Comment by joshmoore** [comment]
@eleanorwilliams : am I right in assuming that this PR is the one that I should test with all of the mapr infrastructure for the upcoming IDR3? And all annotations need to be reproduced?

**Comment by eleanorwilliams** [comment]
Yes, this needs to be tested with mapr and we need to re-load all annotations in idr-demo at some point soon.

**Comment by aleksandra-tarkowska** [comment]
@joshmoore any thoughts about fixing travis?

**Comment by joshmoore** [comment]
```
./idr0019-sero-nfkappab/screenA/idr0019-screenA-annotation.csv
Traceback (most recent call last):
  File "scripts/travis-check.py", line 34, in <module>
    df_default = pandas.read_csv(fn)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/pandas/io/parsers.py", line 562, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/pandas/io/parsers.py", line 325, in _read
    return parser.read()
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/pandas/io/parsers.py", line 815, in read
    ret = self._engine.read(nrows)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/pandas/io/parsers.py", line 1314, in read
    data = self._reader.read(nrows)
  File "pandas/parser.pyx", line 805, in pandas.parser.TextReader.read (pandas/parser.c:8748)
  File "pandas/parser.pyx", line 827, in pandas.parser.TextReader._read_low_memory (pandas/parser.c:9003)
  File "pandas/parser.pyx", line 881, in pandas.parser.TextReader._read_rows (pandas/parser.c:9731)
  File "pandas/parser.pyx", line 868, in pandas.parser.TextReader._tokenize_rows (pandas/parser.c:9602)
  File "pandas/parser.pyx", line 1865, in pandas.parser.raise_parser_error (pandas/parser.c:23325)
pandas.io.common.CParserError: Error tokenizing data. C error: Expected 19 fields in line 2689, saw 20
```

Might be a real issue. I haven't made it to testing on demo3 yet.

**Comment by joshmoore** [comment]
Starting to test now on demo3.

**Comment by eleanorwilliams** [comment]
I've regenerated the annotation.csv file for idr0019, so hopefully fixed now.

**Comment by joshmoore** [comment]
Discussed with @eleanorwilliams and @aleksandra-tarkowska : merging this now. @aleksandra-tarkowska will open her changes on top of this PR, and further fixes will be in separate PRs. Note: if we decide to **not** use demo3, then this PR may need to be rolled-back or we will need to branch a separate `demo2` development line.

**Pull request merged**
