### PR TITLE
idr0026 .screen files

### PR DESCRIPTION
**Pull request by simleo**
Adds .screen files for idr0026, together with the code used to generate them.

One peculiarity of this dataset is that image file names have redundant but non-contiguous channel info, e.g.:

```
15-36-34_PMT - PMT [BD2_GREEN] [02]_C00_Time Time0000.ome.tif
15-36-34_PMT - PMT [FD6_FDRED] [02]_C01_Time Time0000.ome.tif
```

where both `[BD2_GREEN]` and `C00` represent the channel and `[02]` represents the field. A pattern like `[<BD2_GREEN,FD6_FDRED>] [02]_C<00,01>` won't work, since it describes two different dimensions (4 files). However, given that:

* for a given pattern, the field tag is constant (each pattern corresponds to a field)
* the two channel-related elements vary together

a valid pattern block for the C dim can be formed by simply merging all three elements together, i.e., `<[BD2_GREEN] [02]_C00,[FD6_FDRED] [02]_C01>`. `AxisTypes` and `ChannelNames` entries have been added, respectively, to force the first dim to be interpreted as C ("PMT" is not a standard C prefix) and to set the channel names based on the first element (e.g., `BD2_GREEN`).

`check_screen` output:

```
% find screens -type f | while read f; do python ~/git/idr-metadata/scripts/check_screen.py -e -v "${f}"; done
checking 'screens/3.49.6-3.140922_11-33-57.screen'
files: 480 (missing: 0)
checking 'screens/3.49.6-3.140922_13-02-44.screen'
files: 512 (missing: 0)
checking 'screens/3.50.6-3.140922_11-36-07.screen'
files: 1420 (missing: 0)
checking 'screens/3.55.6-3.140922_15-36-34.screen'
files: 1200 (missing: 0)
checking 'screens/3.57.6-3.140922_15-20-05.screen'
files: 880 (missing: 0)
checking 'screens/3.64.6-3.NONE.screen'
files: 1170 (missing: 0)
checking 'screens/3.64.9-6.141023_12-21-30.screen'
files: 1125 (missing: 0)
checking 'screens/3.65.6-3.141020_15-39-00.screen'
files: 720 (missing: 0)
checking 'screens/3.65.6-3.141020_17-15-07.screen'
files: 810 (missing: 0)
checking 'screens/3.65.9-6.141023_15-45-09.screen'
files: 1149 (missing: 0)
checking 'screens/3.66.6-3.141020_15-41-29.screen'
files: 705 (missing: 0)
checking 'screens/3.66.6-3.141020_17-15-27.screen'
files: 828 (missing: 0)
checking 'screens/3.66.9-6.141020_15-41-29.screen'
files: 705 (missing: 0)
checking 'screens/3.66.9-6.141020_17-15-27.screen'
files: 828 (missing: 0)
checking 'screens/3.66.9-6.141023_15-49-01.screen'
files: 1125 (missing: 0)
checking 'screens/3.67.6-3.141020_11-39-56.screen'
files: 1305 (missing: 0)
checking 'screens/3.67.9-6.141023_12-39-26.screen'
files: 975 (missing: 0)
checking 'screens/7.48.10-3.140926_12-18-43.screen'
files: 864 (missing: 0)
checking 'screens/7.51.10-3.140926_10-43-58.screen'
files: 924 (missing: 0)
checking 'screens/7.52.10-3.140926_14-51-38.screen'
files: 1600 (missing: 0)
checking 'screens/7.53.10-3.140926_18-40-48.screen'
files: 1720 (missing: 0)
checking 'screens/7.54.10-3.140926_18-36-07.screen'
files: 1716 (missing: 0)
checking 'screens/7.56.10-3.140926_14-52-18.screen'
files: 1296 (missing: 0)
```

### CODE REVIEW

**Comment by simleo** [comment]
The last 4 commits add a dataset arrangement based on `.pattern files`. Individual files have been renamed to drop the redundant numeric channel info and change the extension to `.tif` since they are not valid ome-tiffs.

**Comment by joshmoore** [comment]
This is current conflicting with gh-210.

**Comment by joshmoore** [comment]
Can you add a bulk.yml here as well?

```
---
include: "../../bulk.yml"
path: "idr0026-experimentA-filePaths.tsv"
columns:
    - target
    - path
```

**Comment by joshmoore** [comment]
symlinks have been generated and added to `/nfs/bioimage`. Waiting on the synchronization.

**Comment by joshmoore** [comment]
I may have done something wrong, but the symlink directory was created without the PNAS subdirectory.

**Comment by joshmoore** [comment]
Seeing `Error untangling IFDs; the OME-TIFF file may be malformed (IFD #1917 missing).` in the logs

**Comment by joshmoore** [comment]
Discussion today points to needing to re-write the files as opposed to just symlinking away the `.ome.tif` ending.

**Comment by simleo** [comment]
@joshmoore are you getting the `Error untangling IFDs` in all cases or just for `3.49.6-3.140922_11-33-57.*`? Only files in `mouse 49/day 6-3/time lapse/140922_11-33-57` have an ome-xml comment in them, so if the problem is a mismatch between binary TIFF data and ome-xml metadata, all patterns except `3.49.6-3.140922_11-33-57.*` should be ok with just the renaming done so far.

/cc @eleanorwilliams @sbesson

**Comment by joshmoore** [comment]
Apologies.  Looking for the first file, it appears that these error messages were from idr0030. I didn't realize that was happening at the same time.

**Comment by simleo** [comment]
OK, so all patterns except `3.49.6-3.140922_11-33-57.*` should be fine. Re: `3.49.6-3.140922_11-33-57.*`, we can avoid rewriting the files via https://github.com/openmicroscopy/bioformats/pull/2774 (just need to add 5 comment lines here).

**Comment by simleo** [comment]
@joshmoore update on the `Error untangling IFDs` issue: I saw (many) such errors while trying to open a file from `3.49.6-3.140922_11-33-57` with Fiji (in the console), so maybe the ones you saw were from idr0026 after all (they might *also* be in idr0030 ofc).

**Comment by simleo** [comment]
* Removed my TSV together with the code that generated it
* Cherry-picked everything from #210

**Comment by simleo** [comment]
> I may have done something wrong, but the symlink directory was created without the PNAS subdirectory.

You have to include it in the argument:

```
./symlink_all /uod/idr/filesets/idr0026-weigelin-immunotherapy/20170222-symlinks/PNAS_2015
```

**Comment by simleo** [comment]
56b05fa adds channel names settings as requested by @eleanorwilliams. Requires latest version of https://github.com/openmicroscopy/bioformats/pull/2774

**Comment by joshmoore** [comment]
Import running on test34

**Comment by simleo** [comment]
Closing in favor of #227.

**Pull request closed without merging**
