### PR TITLE
Bulkmap fixes (IDR-0.3.3)

### PR DESCRIPTION
**Pull request by eleanorwilliams**
fixes to bulkmap config files for missing organism in idr0012-A and missing compound in idr0019

### CODE REVIEW

**Comment by eleanorwilliams** [comment]
for 0.3.2 release

**Comment by joshmoore** [comment]
Bumping to 0.3.3

**Comment by eleanorwilliams** [comment]
I removed Compound = none from the idr0019-A library file to match what Ola has changed in the annoation.csv in https://github.com/eleanorwilliams/idr-metadata/pull/22/commits/f1822bfbe0b7011ff520e76b0e5c9985da8f9ee5

**Comment by joshmoore** [comment]
Merging for testing 0.3.3 against test33

**Pull request merged**
