### PR TITLE
For discussion: Storing feature calculation metadata

### PR DESCRIPTION
**Pull request by manics**
Since we don't have a system for tracking the provenance of features this would be one way to ensure the validity of copied files.

### CODE REVIEW

**Comment by simleo** [comment]
+1 for adding paths and checksums. In the READMEs we should also add info on the serialize step, where available.

**Comment by joshmoore** [comment]
Cool. Let's start with this structure then. @simleo : I could likely use some help getting the previous runs from the IDR Dataset Map into this format. @simleo and @eleanorwilliams : primary question for me is the directory. Do we:

|                                                                                             | pros                       | cons                                                                                                      |
|---------------------------------------------------------------------------------------------|----------------------------|-----------------------------------------------------------------------------------------------------------|
| take this as is                                                                             | simple                     | gives us a second per-study hierarchy in this repo                                                        |
| put a `features/` directory under each study directory                                      | keeps study info together  | "features" isn't quite at the same level as "studies" but perhaps ok                                      |
| put this in a separate idr-features repo (along with gh-237)                                | less noise on idr-metadata | something else to keep up; we'd also want to extract some files from here to that repo                    |
| start putting these in per-study repos like https://github.com/IDR/idr0000-lastname-example | cleanest                   | we wouldn't be able to represent that in this repo until _all_ the files from a given study were migrated |

cc: @idr/analysis - A next step might be to try to access it programmatically from notebooks.

Merging.

**Comment by simleo** [comment]
I like options one and two. Opening more repos might make thing too confusing / complicated.

**Comment by joshmoore** [comment]
This repository is already filled with gargantuan files. Merging this to simplify my life on orca-3 while I figure out the state of things, but for reasons I'll explain (datapackages!) I'm strongly inclined towards **four**.

**Comment by simleo** [comment]
Re: getting info on the previous runs, at least for the oldest ones we don't have the command lines anymore. However, we can get info 1) from the Trello cards and 2) from the output files. To facilitate the latter, I have just opened https://github.com/openmicroscopy/pydoop-features/pull/50.

**Comment by joshmoore** [comment]
Nice idea. Thanks!

**Pull request merged**
