### PR TITLE
idr0038 metadata update and multi-component study parsing

### PR DESCRIPTION
**Pull request by sbesson**
## Summary

See https://trello.com/c/Zk2cX2gr/3-metadata-updates-part-2

Primarily this PR makes updates the the idr0038 study file to match the live annotations and add the metadata of the [recent publication](https://www.ncbi.nlm.nih.gov/pubmed/30048451). To validate this, this PR also tackles the problem of parsing and checking multi-screens and/or multi-experiments studies using the `study_parser`.

## Changes

The main changes are around API of the `study_parser` to accomodate for multi-screen/multi-experiment studies and also validate top-level study containers when existing:
- the legacy `TextPrinter` is completely dropped in favor of the JSON serialization
- the logic of `JsonPrinter` and `Object` is combined into a single class (currently `Formatter` - better name welcome) which constructs a dictionary representation of a StudyParser object
- the JSON output of a study with the `--report` option now has the study metadata at the top-level. Study screens and experiments are contained within the corresponding fields.
- the `map` field is modified from a dictionary to a list of dictionaries with single-key value pairs. This change is required to conserve the key/value pairs ordering as well as handle duplicate keys like publications.

## Testing

The metadata update changes for idr0038 have been applied on the testing resource. The description/map of the various projects can be compared to the ones on the production resource. In addition, the various arguments of the study_parser script should be reviewed including the validation argument:

```

PYTHONPATH=/path/to/OMERO.py/lib/python/ python pyidr/study_parser.py idr0038-held-kidneylightsheet/idr0038-study.txt --check
```

and the report argument:

```
PYTHONPATH=/path/to/OMERO.py/lib/python/ python pyidr/study_parser.py idr0038-held-kidneylightsheet/idr0038-study.txt --report [--inspect]
```

These changes should not affect the parsing of existing studies (tested by Travis) as well as the validation of existing studies. To test the latter, the `--check` command above can be executed against a few of the [reviewed studies](https://trello.com/c/I2rbYM9L/48-metadata-updates).

## Discussion

Probably outwith the scope of this PR, the current JSON representation is very close to the composition of a study to i.e.

```
{ 

  "description": ...,
  "experiments": [
      {
         "description": ...,
         "map": ...,
         "name": ...
         "files": ...
      },...
    ]
   "map": ...,
   "name": "idr0038-held-kidneylightsheet", 
    "screens": [],
}
```

An alternate representation would be to store all the annotated containers (top-level study, experiments, screens) as a flat list e.g.

```
{ 
  "resources": [
      {
         "type":...,
         "description": ...,
         "map": ...,
         "name": ...,
          "files": ...
      },...
    ]
   "name":"idr0038-held-kidneylightsheet", 
}
```

### CODE REVIEW

**Comment by joshmoore** [comment]
No immediate objections to the changes. Without walking more closely through the code, some of the mutating methods versus returning methods surprised me a bit.

Re: the `resources` suggestions -- I think that might be part of a bigger discussion about where we want to go and, for example, whether or not it'll handle folders, etc.

Note: I don't have a comparison to before this PR, but travis shows:

```
jamoore$ pbpaste | sort | grep -v INFO | uniq -c
   1 WARNING:pyidr.study_parser:Unknown key: Additional File
   1 WARNING:pyidr.study_parser:Unknown key: Additional File description
   1 WARNING:pyidr.study_parser:Unknown key: Study BioStudies Accession
   1 WARNING:pyidr.study_parser:Unknown key: Study Copyright Pelet et al
   2 WARNING:pyidr.study_parser:Unknown key: Study DOI
  35 WARNING:pyidr.study_parser:Unknown key: Study External URL
  22 WARNING:pyidr.study_parser:Unknown key: Study Organism Term Accession
  13 WARNING:pyidr.study_parser:Unknown key: Study Organism Term Accession Number
  35 WARNING:pyidr.study_parser:Unknown key: Study Organism Term Source REF
   2 WARNING:pyidr.study_parser:Unknown key: Study PMC ID
  35 WARNING:pyidr.study_parser:Unknown key: Study Person Address
  35 WARNING:pyidr.study_parser:Unknown key: Study Person Email
  35 WARNING:pyidr.study_parser:Unknown key: Study Person First Name
  35 WARNING:pyidr.study_parser:Unknown key: Study Person Last Name
  35 WARNING:pyidr.study_parser:Unknown key: Study Person Roles
   1 WARNING:pyidr.study_parser:Unknown key: Study PubMed ID
  34 WARNING:pyidr.study_parser:Unknown key: Study Public Release Date
  22 WARNING:pyidr.study_parser:Unknown key: Study Type Term Accession
  13 WARNING:pyidr.study_parser:Unknown key: Study Type Term Accession Number
  35 WARNING:pyidr.study_parser:Unknown key: Study Type Term Source REF
   9 WARNING:pyidr.study_parser:Unknown key: Study Version History
   2 WARNING:pyidr.study_parser:Unknown key: Term Source File
  35 WARNING:pyidr.study_parser:Unknown key: Term Source Name
  33 WARNING:pyidr.study_parser:Unknown key: Term Source URI
   1 WARNING:pyidr.study_parser:Unknown key: Term Source Version
```

**Comment by joshmoore** [comment]
>  If we agree with the structure of the JSON output for now...

I have no hard-dependency on the JSON output at the moment, so the state of this PR certainly works for me and we can iterate quickly.

**Comment by sbesson** [comment]
Agreed with the fast iteration on the API if @dominikl is happy with the changes as well.

**Comment by dominikl** [comment]
Looks good, thanks @sbesson 👍

**Comment by sbesson** [comment]
Thanks both. As discussed above, merging and applying idr0038 metadata updates for the next IDR release.

**Pull request merged**
