### PR TITLE
idr0012: Add roi import plugin

### PR DESCRIPTION
**Pull request by dominikl**
CLI plugin to import the ROIs from the hdf5 file created by #289 .
Doesn't work yet, because there are 4 fields / well in the data, but only 2 fields / well in OMERO! 
See my comment on https://trello.com/c/hjEUogsi/23-rois-idr0012-fuchs

### CODE REVIEW

**Comment by joshmoore** [comment]
Finally got a chance to compare this and gh-287. We may need to discuss the naming collision here: there won't be a way to activate both of the plugins at the same time. Perhaps that's ok, since you'll only ever be running one at a time, but there would be no way to have them, e.g., all on the PYTHONPATH at the same time. This makes me think of a RoiReader and whether or not we should detect these "formats" at runtime.

**Comment by dominikl** [comment]
That's true. I.e. have only one `idroi` command (still looking for a better name btw) and specify format via an extra argument `--format=idr0012`, `--format=idr0016`, etc. ?

**Comment by joshmoore** [comment]
Something like that, yes. It might be that as with `readers.txt` from Bio-Formats, we can specify the (Python) class name for `--format` in addition to some well-known formats (`cellprofiler`, etc)

**Comment by dominikl** [comment]
Replaced by #292

**Pull request closed without merging**
