### PR TITLE
Add .screen files for idr0016

### PR DESCRIPTION
**Pull request by simleo**
Adds idr0016 `.screen` files and the scripts used to generate them.

**NOTE:** Some wells are completely missing (as in other projects), while some are missing one or more fields. Since having different numbers of fields for different wells is not supported, these wells have also been marked as empty. See `idr0016-wawer-bioactivecompoundprofiling/generate_screens/make_all.out` for details.

The other report file is `idr0016-wawer-bioactivecompoundprofiling/generate_screens/stats.txt`, a table with the total number of files for each plate (row) and channel (column).

### CODE REVIEW

**Comment by joshmoore** [comment]
@simleo : could you cherry-pick https://github.com/joshmoore/idr-metadata/commit/5429b20016461b0755836b064045d53f8965ffeb please

Tested with `[omero@b3f7795a7202 omero]$ OMERO.server/bin/omero import ---bulk=idr-metadata-merge/idr0016-wawer-bioactivecompoundprofiling/screenA/idr0016-screenA-bulk.yml -f` on mini-4

Note: I'm currently getting an exception with build 78:

```
2016-05-02 16:18:44,581 719        [      main] ERROR     ome.formats.importer.cli.ErrorHandler - FILE_EXCEPTION: /opt/omero/idr-metadata-merge/idr0016-wawer-bioactivecompoundprofil
ing/screenA/../screens/20585.screen
java.lang.NumberFormatException: For input string: "ER"
```

Just checking now if your PR(s) got included.

**Comment by joshmoore** [comment]
BIOFORMATS-maven/59/ says yes, but considering this is named 5.1.8 rather than 5.1.8-SNAPSHOT as I expected, I'll look deeper.

**Comment by joshmoore** [comment]
`bin/omero import -f` is currently running on mini4. I'll report back ASAP.

**Comment by simleo** [comment]
The `NumberFormatException` likely means that the build is missing openmicroscopy/bioformats@9c09b57

**Comment by joshmoore** [comment]
Agreed:

 * https://github.com/openmicroscopy/openmicroscopy/pull/4626
 * https://github.com/openmicroscopy/bioformats/pull/2390

were needed to get everything in sync. Sorry for the noise.

**Comment by joshmoore** [comment]
"20585" (plate:4403) successfully went in :+1:

**Pull request merged**
