### PR TITLE
Add idr0047 and idr0053 to the list of repository modules

### PR DESCRIPTION
**Pull request by sbesson**

### CODE REVIEW

**Comment by joshmoore** [comment]
:+1: Both submodules look to point at their master branches.

**Comment by sbesson** [comment]
@dominikl the failures of https://travis-ci.org/IDR/idr-metadata/builds/479291158 points at duplicate column names (`Protocol REF`) in the annotation file of idr0047. We might want to choose whether these rows should be differentiated or combined.

**Comment by dominikl** [comment]
I already changed that, should be only `Protocol` must have forgotten to commit.
How do you check the submodules btw, ran `git submodule update --init --recursive`, then for example `idr0047-neuert-yeastmRNA` is created, but it's empty.

**Comment by dominikl** [comment]
Tried again, works now. 👍

**Pull request merged**
