### PR TITLE
idr0023 - fixed dataset names, and changed filePaths.txt to filePaths.tsv

### PR DESCRIPTION
**Pull request by eleanorwilliams**
@joshmoore 
I've fixed the incorrect dataset names so now there will be one all_particles.tif per dataset.  
I have also changed filePaths.txt to filePaths.tsv and updated the bulk.yml to point to the .tsv file. 

3 datasets will need to have the raw images reloaded (or just start again from scratch for the whole thing). 
Seh1-aa342-360_antibody_1
Seh1-aa342-360_antibody_2
Seh1-aa342-360_antibody_3

What I'm not sure about is how to put a pull request in to merge this to https://github.com/IDR/idr-metadata/pull/93.   I think I might be getting my git repository in a muddle.

### CODE REVIEW

**Comment by joshmoore** [comment]
@eleanorwilliams, 2 questions:

 * is there anything in gh-93 that's not here? If not, I'll just close 93.
 * does this require a reimport? Or do you think I can handle the renamings manually?

**Comment by eleanorwilliams** [comment]
@joshmoore.  

- Think you can just close https://github.com/IDR/idr-metadata/pull/93. 
- Two of the all_particles.tif files are in the wrong datasets.   

1.  /uod/idr/incoming/idr0023-szymborska-nuclearpore/20160419-original/EllenbergGroupData_for_IDR/Nucleoporins/Seh1/Seh1-FL_antibody_rb/120805_seh1_2/AllParticles/all_particles.tif   was in Seh1-FullLength_antibody_1 and should be in Seh1-FullLength_antibody_2
2. /uod/idr/incoming/idr0023-szymborska-nuclearpore/20160419-original/EllenbergGroupData_for_IDR/Nucleoporins/Seh1/Seh1-FL_antibody_rb/120807_seh1_3/AllParticles/all_particles.tif was in Seh1-FullLength_antibody_2 and should be in Seh1-FullLength_antibody_3. 

If you can identify which of the all_particles.tif files come from which source go ahead and move them, other wise might be easier to reload.

**Comment by joshmoore** [comment]
@eleanorwilliams -- I should definitely be able to identify them. Looking at the currently imported data, though, it looks like it's the `aa342-360` directories which have issues as opposed to the `FullLength` ones. Could that be the case?

**Comment by eleanorwilliams** [comment]
My mistake, it is the aa342-360 that should be moved.  My last comment about the files is wrong.

**Comment by joshmoore** [comment]
Patch needed:

```
[omero@minke experimentA]$ git diff
diff --git a/idr0023-szymborska-nuclearpore/experimentA/idr0023-experimentA-bulkmap-config.yml b/idr0023-szymborska-nuclearpore/experimentA/idr0023-experimentA-bulkmap-config.yml
index 82a24dd..9bde9c5 100644
--- a/idr0023-szymborska-nuclearpore/experimentA/idr0023-experimentA-bulkmap-config.yml
+++ b/idr0023-szymborska-nuclearpore/experimentA/idr0023-experimentA-bulkmap-config.yml
@@ -37,7 +37,7 @@ columns:
     include: yes
   - name: Gene Symbol Synonyms
     include: yes
-  - name: Antibody
+  - name: Experimental Condition [Antibody]
     include: yes
   - name: Phenotype 1
     include: yes
```

Otherwise, loaded!

**Comment by eleanorwilliams** [comment]
@joshmoore Thanks! Obviously I did too much messing around with these datasets. Will fix this last issue and push

**Comment by joshmoore** [comment]
:+1:

**Pull request merged**
