### PR TITLE
Fix relative paths in plates.tsv files

### PR DESCRIPTION
**Pull request by simleo**
Relative paths in `idr*/screen*/*plates.tsv` follow a mixed convention where the path  is either relative to `idr*/screen*` or to its parent. The former convention seems more "natural" (a path listed in a file is relative to the same directory that hosts the file) and it's the one expected by `scripts/celery/serialize`. This PR changes all files that follow the latter convention to follow the former instead.

### CODE REVIEW

**Comment by joshmoore** [comment]
Thanks for the cleaning, @simleo. Likely the reason that I started moving away from `../` was that it ends up in the `clientPath` value in OMERO. But considering the current mix we have, that's probably not an issue. An alternative would be to go absolute everywhere using `/idr/filesets/...`. 

What does serlialize use the paths for?

**Comment by simleo** [comment]
> An alternative would be to go absolute everywhere using `/idr/filesets/...`

In some studies the paths refer to `.screen` files in this repo. To go absolute everywhere we'd have to deploy those to `/idr/filesets`.

> What does serlialize use the paths for?

They are the input files, the ones that get converted to Avro.

**Comment by joshmoore** [comment]
> They are the input files, the ones that get converted to Avro.

And serialize is reading them from the TSVs?

**Comment by joshmoore** [comment]
> In some studies the paths refer to .screen files in this repo.

Yes, which has turned out to be dangerous since a git checkout can alter the data. (They are symlinked into ManagedRepository!)

**Comment by simleo** [comment]
@joshmoore `serialize` expects a PLATE_NAME to PLATE_FILE 2-column TSV mapping (as did the original gists by @manics). Some of the `idr*/screen*/*plates.tsv` can be used as-is for this purpose, but there are two cases where this fails:

* The one addressed by this PR
* TSVs where paths in the second column point to a directory rather than a file. In these cases I've simply used a locally updated version of the TSV to drive the script

**Comment by joshmoore** [comment]
Ok. That's what I was worried about. Perhaps we can extend what's currently in place w.r.t bulk import (or wrap it with idr.py etc) in order to have an independent plate_name to plate_file mapping.

**Comment by joshmoore** [comment]
Note: this likely invalidates some of the import scripts in `demo2:~omero/other-imports` but that's fairly easy to correct when/if we need to re-import.

**Pull request merged**
