### PR TITLE
Change /idr paths to /uod/idr

### PR DESCRIPTION
**Pull request by manics**
Transformed with OS X find and sed:
`find idr00* -type f -exec sed -i '' -Ee 's%(^| )/idr/%\1/uod/idr/%' "{}" \;`

Then excluded `*.{csv,log,md,out,sh,txt,xlsx}`, apart from `idr0001-graml-sysgro/SysgroAllPlatesFromLibraryFiles.txt` which sneaked past with a `\ No newline at end of file` change.

This includes https://github.com/IDR/idr-metadata/pull/71

### CODE REVIEW

**Comment by manics** [comment]
The alternative is to keep all paths as `/idr` and create symlink `/uod/idr` -> `/idr`.

**Comment by joshmoore** [comment]
The only caveat to this is that this will completely break narwhal if ever checked out there. I wonder if it's time to branch.

**Comment by manics** [comment]
This will also be used at the EBI, so keeping/symlinking `/idr` could also be justified.

**Comment by joshmoore** [comment]
With the recent decision to remove `/uod/idr` from narwhal and replace with a symlink to `/idr` this should be fine. Merging.

**Pull request merged**
