### PR TITLE
idr0012: annotations & bulk files

### PR DESCRIPTION
**Pull request by joshmoore**
Replaces gh-78 via rebasing onto origin/master

### CODE REVIEW

**Comment by joshmoore** [comment]
@eleanorwilliams : a test run required the changes below.

```
diff --git a/idr0012-fuchs-cellmorph/screenA/idr0012-screenA-bulkmap-config.yml b/idr0012-fuchs-cellmorph/screenA/idr0012-screenA-bulkmap-config.yml
index f242240..f897bc4 100644
--- a/idr0012-fuchs-cellmorph/screenA/idr0012-screenA-bulkmap-config.yml
+++ b/idr0012-fuchs-cellmorph/screenA/idr0012-screenA-bulkmap-config.yml
@@ -167,20 +167,12 @@ columns:
     include: yes
   - name: Phenotype 12
     include: yes
-  - name: Phenotype 12 Term Name a
+  - name: Phenotype 12 Term Name
     include: yes
-  - name: Phenotype 12 Term Accession a
+  - name: Phenotype 12 Term Accession
     include: yes
-  - name: Phenotype 12 Term Accession a
-    clientname: Phenotype 12 Term Accession a URL
-    clientvalue: http://purl.obolibrary.org/obo/{{ value }}
-    include: yes
-  - name: Phenotype 12 Term Name b
-    include: yes
-  - name: Phenotype 12 Term Accession b
-    include: yes
-  - name: Phenotype 12 Term Accession b
-    clientname: Phenotype 12 Term Accession b URL
+  - name: Phenotype 12 Term Accession
+    clientname: Phenotype 12 Term Accession URL
     clientvalue: http://purl.obolibrary.org/obo/{{ value }}
     include: yes
   - name: Phenotype 13
```

**Comment by eleanorwilliams** [comment]
Thanks for testing.  Should I fix on this branch?

**Comment by joshmoore** [comment]
If that sounds like the correct fix to you, I can push to this PR.

**Comment by eleanorwilliams** [comment]
@joshmoore  Yes fix is good.

**Comment by joshmoore** [comment]
```
INFO:omero.util.populate_metadata:Created 38976 MapAnnotations
```

**Pull request merged**
