### PR TITLE
Feature updates on top of gh-239

### PR DESCRIPTION
**Pull request by joshmoore**
@manics managed the full workflow for mito/screenA. I'll keep notes and update the feature files for mito/screenB cellmorph/screenA and any other runs that are processed in this (or follow-up) PR(s)

see:
 * gh-239
 * gh-237

TODOs:
 * [ ] directory names: idr0013 uses `_` where idr0012 uses `-`
 * [ ] rename TSV files to omit screen ID
 * [ ] Makefile
 * [ ] deal with non-standard files (HT48.h5)
 * [ ] workaround need to `chmod 777 tables/`

### CODE REVIEW

**Comment by joshmoore** [comment]
First run failed with:

``
[jamoore@idr0-slot3 celery]$ python collate --out-dir /uod/idr/features/idr0013-neumann-mitocheck/screenB-l_W672_H512_offsetx336_offsety256_x1344_y1024 /uod/idr/scratch/idr*
processing: /uod/idr/scratch/idr0-slot2/idr0013-screenB
processing: /uod/idr/scratch/idr0-slot2/idr0012-screenA
processing: /uod/idr/scratch/idr1-slot2/idr0013-screenB
Traceback (most recent call last):
  File "collate", line 101, in <module>
    main(sys.argv)
  File "collate", line 97, in main
    copy_if_newer(source_fn, target_fn, dry_run=args.dry_run)
  File "collate", line 47, in copy_if_newer
    shutil.copy2(source_fn, target_fn)
  File "/usr/lib64/python2.7/shutil.py", line 130, in copy2
    copyfile(src, dst)
  File "/usr/lib64/python2.7/shutil.py", line 82, in copyfile
    with open(src, 'rb') as fsrc:
IOError: [Errno 21] Is a directory: '/uod/idr/scratch/idr1-slot2/idr0013-screenB/LTValidMitosisSon384Plate02_05'
[jamoore@idr0-slot3 celery]$ python collate --out-dir /uod/idr/features/idr0013-neumann-mitocheck/screenB-l_W672_H512_
```

Correct run was:

```
[jamoore@idr0-slot3 celery]$ python collate --out-dir /uod/idr/features/idr0013-neumann-mitocheck/screenB-l_W672_H512_offsetx336_offsety256_x1344_y1024 /uod/idr/scratch/idr*/idr0013-screenB/
processing: /uod/idr/scratch/idr1-slot2/idr0013-screenB/LTValidMitosisSon384Plate02_05
processing: /uod/idr/scratch/idr1-slot2/idr0013-screenB/LTValidMitosisSon384Plate01_03
...
```

and

```
[jamoore@idr0-slot3 celery]$ python collate --out-dir /uod/idr/features/idr0012-fuchs-cellmorph/screenA-l-W672-H512--offset-x0--offset-y0-x1344-y1024 /uod/idr/scratch/idr*/idr0012-screenA/
```

**Comment by joshmoore** [comment]
```
[jamoore@idr0-slot3 features]$ find . -name "*.tsv"
./idr0005-toret-adhesion/screenA/tables/intermediate/map_screen_597.tsv
./idr0012-fuchs-cellmorph/screenA/tables/intermediate/map_screen_1202.tsv
./idr0013-neumann-mitocheck/screenA-l_W672_H512_offsetx336_offsety256_x1344_y1024/tables/map_screen_1101.tsv
./idr0013-neumann-mitocheck/screenA-l_W672_H512_offsetx336_offsety256_x1344_y1024/tables/map_screen_1101-dedup.tsv
./idr0013-neumann-mitocheck/screenA/tables/intermediate/map_screen_1101.tsv
./idr0013-neumann-mitocheck/screenB/tables/intermediate/map_screen_1302.tsv
./idr0009-simpson-secretion/screenA/tables/intermediate/map_screen_251.tsv
./idr0009-simpson-secretion/screenB/tables/intermediate/map_screen_803.tsv
./idr0008-rohn-actinome/screenB/tables/map_screen_206.tsv
./idr0002-heriche-condensation/screenA/tables/intermediate/map_screen_102.tsv
```

**Comment by joshmoore** [comment]
idr0012 collation took:

```
real    82m34.998s
user    0m7.268s
sys     0m6.347s
```

**Comment by manics** [comment]
Can't see any obvious reason not to merge this.

**Comment by joshmoore** [comment]
Ok. I'll move the TODOs to a card.

**Comment by joshmoore** [comment]
https://trello.com/c/EVZw2SBe/53-feature-storage-todos

**Pull request merged**
