### PR TITLE
idr0040 metadata

### PR DESCRIPTION
**Pull request by dominikl**
Builds on top of @bramalingam 's PR #295 .
Adds `study.txt` , `bulkmap-config` and `annotation.csv`.

For the `annotation.csv` I basically merged the four provided Excel files together, hope that makes sense. For the `study.txt` I took a `study.txt` of a previous IDR project and updated the fields with the author provided information in the Excel file. The syntax of this file looks pretty strange, is there actually one? Or is that just an informative file which doesn't get machine processed in any way?

Someone with more IDR experience should check this PR. Maybe @eleanorwilliams could have a brief look and check if this looks sensible?

### CODE REVIEW

**Comment by joshmoore** [comment]
Yaml linting:

```
  91:1      error    too many blank lines (1 > 0)  (empty-lines)
```

**Comment by dominikl** [comment]
I think I have to go over the 'protocol' section in the `study.txt` again. Although I can't make sense of the protocol description in the Excel file: They mention three different protocols in the rows (Induction, Dose response, Mating), but then five protocols in the columns (Overnight + 4h, Pheromone treatment, Time-lapse induction, Time-lapse Mating, YeastQuant analysis). How does that go together?

**Comment by dominikl** [comment]
Another remark: Just noticed that the annotion.csv is far from ready, have to regenerate it, **not ready for review yet**.

**Comment by dominikl** [comment]
Last commit renames everything to 'experimentA' (as there is only one) and includes the full image file tsv again. Shall I start the full import once travis is green @sbesson ?

**Comment by sbesson** [comment]
Fantastic, thanks @dominikl. Once this PR is validated, yes let's start the full import over the week-end.

**Comment by dominikl** [comment]
Thanks a lot @eleanorwilliams  for reviewing! Yes, I was a bit confused about the `MAT@`. But don't you think `MAT@` should be `MATalpha`, as there are `MATa` and `MAT@` mentions in the excel files?

**Comment by eleanorwilliams** [comment]
@dominikl - yes it could well be alpha for the Mat@ - I haven't seen the Excel files and didn't look too closely. And thinking about it more, you should really use an ontology term so that its always the exact same terms that are used in case one day we want to be to search across IDR experiments by mating type.  I usually use the Experimental Factor Ontology but other ontologies will also contain these terms.  Its just a case of picking one and sticking with it. EFO has both mating type a and alpha listed: https://www.ebi.ac.uk/ols/ontologies/efo/terms?iri=http%3A%2F%2Fwww.ebi.ac.uk%2Fefo%2FEFO_0001268. So "mating type a" would replace "Mata" in the Characteristics [Mating Type] column.  And "mating type a X mating type alpha" instead of "Mata X MATalpha".  Ideally you would put in Term Source REF and Term Source Accession columns in after the Characteristics [Mating Type] column with EFO and then the accessions.  Where there are two mating types you could just put the two accessions separated by a semi colon (i.e. EFO_0001275;EFO_0001270).  These accession don't appear in IDR just now.  I think I would also change the value "Mata X EMPTY" to just "mating type a" as its only mating type a cells that are there and the treatment column gives more information.

**Comment by dominikl** [comment]
Thanks again, I'll include your suggestions!

**Comment by dominikl** [comment]
Moved to separate repository: https://github.com/IDR/idr0040-aymoz-singlecell/

**Comment by joshmoore** [comment]
Thanks, @dominikl. If you think any of the history here is valuable, happy to help filter it out. Also, what about the files that were outside of `idr0040.../`?

**Comment by dominikl** [comment]
As @sbesson suggested I moved the 'script' files from the top level `scripts` directory into a `scripts` directory within idr0040. They are pretty specific, so doesn't really make sense to have them in the top level directory. That should be all files which were outside `idr0040`.

It would definitely be good to keep the history. This PR won't disappear although it's closed, will it? I thought it'd be enough to have a link back to this PR, isn't it?

**Comment by joshmoore** [comment]
re: scripts -- :+1:

re: history -- this thread won't go away, but the commits can be assumed to eventually disappear. If that's ok, then there's nothing that needs doing.

**Comment by dominikl** [comment]
I thinks that's alright 👍

**Pull request closed without merging**
