### PR TITLE
idr0025: .screen files

### PR DESCRIPTION
**Pull request by simleo**
Adds .screen files for idr0025, together with the code used to generate them.

As discussed elsewhere, since V indices are inconsistent, they are overridden according to sub-directory names (`A?B? -> 0-3` and `E?F? -> 4-7`).

Note that, although all three files seem to be ok (checked with `scripts/check_screen.py -e -v`), bioformats fails to read the patterns correctly. For instance:

```
% cat test.pattern 
/uod/idr/[...]/A 0_L 0_S 0_U 0_V 4_X 0_Y 0_Job(Seq.Scan) 1 01 01 01_001_z0_ch0<0-2>.tif
% ./showinf -nopix -nometa test.pattern 
[...]
TCSReader initializing /uod/idr/filesets/idr0025-stadler-proteinatlas/20160525-rawdata/10x images plate 2/plate 2 A1B1 ab 1 DDX3Y/Sequence/Loop_ 0/A 0_L 0_S 0_U 0_V 4_X 0_Y 0_Job(Seq.Scan) 1 01 01 01_001_z0_ch00.tif
[...]
Series count = 1
Series #0 :
	Image count = 48
	RGB = false (1) 
	Interleaved = false
	Indexed = true (false color, 8-bit LUT: 3 x 256)
	Width = 2048
	Height = 2048
	SizeZ = 1
	SizeT = 16
	SizeC = 3
	Thumbnail size = 128 x 128
	Endianness = intel (little)
	Dimension order = XYCTZ (certain)
	Pixel type = uint8
	Valid bits per pixel = 8
	Metadata complete = false
	Thumbnail series = false
```

I.e., it's using all 48 files in the directory instead of the three described by the pattern, and finding an extra T dimension. This is likely some automatic behaviour from `TCSReader`, since simply pointing `showinf` to a single `.tif` file in the directory leads to the same result.

Plate 1 has yet another problem:

```
Exception in thread "main" loci.formats.UnknownFormatException: Unknown file format: /uod/idr/filesets/idr0025-stadler-proteinatlas/20160525-rawdata/10x images plate 1/plate 1 E9 ab 21 CGRRF1/Sequence/Loop_ 0/A 0_L 0_S 0_U 3_V 4_X 0_Y 0_Job(Seq.Scan) 1 01 01 02 01_001_z0_ch00.tif
        at loci.formats.ImageReader.getReader(ImageReader.java:195)
        at loci.formats.ImageReader.fileGroupOption(ImageReader.java:611)
        at loci.formats.ReaderWrapper.fileGroupOption(ReaderWrapper.java:396)
        at loci.formats.FileStitcher.initFile(FileStitcher.java:909)
        at loci.formats.FileStitcher.setId(FileStitcher.java:888)
        at loci.formats.ReaderWrapper.setId(ReaderWrapper.java:651)
        at loci.formats.DimensionSwapper.setId(DimensionSwapper.java:293)
        at loci.formats.in.ScreenReader.initFile(ScreenReader.java:385)
        at loci.formats.FormatReader.setId(FormatReader.java:1433)
        at loci.formats.ImageReader.setId(ImageReader.java:844)
        at loci.formats.ReaderWrapper.setId(ReaderWrapper.java:651)
        at loci.formats.tools.ImageInfo.testRead(ImageInfo.java:1028)
        at loci.formats.tools.ImageInfo.main(ImageInfo.java:1117)
```

If pointed directly to that file, however, `showinf` does not crash, but rather identifies it as a plain TIFF.

### CODE REVIEW

**Comment by simleo** [comment]
bc91b85 adds entries to exclude `TCSReader`. Note that this depends on https://github.com/openmicroscopy/bioformats/pull/2758. With this change, all three plates seem to read as expected, e.g.:

```
Series #0 :
        Image count = 4
        RGB = false (1) 
        Interleaved = false
        Indexed = true (false color, 8-bit LUT: 3 x 256)
        Width = 2048
        Height = 2048
        SizeZ = 1
        SizeT = 1
        SizeC = 4
        Thumbnail size = 128 x 128
        Endianness = intel (little)
        Dimension order = XYCZT (certain)
        Pixel type = uint8
        Valid bits per pixel = 8
        Metadata complete = true
        Thumbnail series = false
```

**Comment by joshmoore** [comment]
```
[jamoore@test34-omero 10x images plate 1]$ for x in *; do ls "$x/Sequence/Loop_ 0/" | grep tif | wc; done | grep " 48 " | wc
      7      21     168
[jamoore@test34-omero 10x images plate 1]$ for x in *; do ls "$x/Sequence/Loop_ 0/" | grep tif | wc; done | grep " 64 " | wc
     17      51     408
```

Looks like the empty wells are those where only `ch<0-2>.tif` is used rather than `ch<0-3>.tif`

**Comment by joshmoore** [comment]
Trying now.

**Comment by joshmoore** [comment]
With `Exclude = TCSReader`, I still see a number of initializations like:

```
2017-02-27 13:10:03,743 INFO  [                loci.formats.ImageReader] (.Server-15) TCSReader initializing /uod/idr/filesets/idr0025-stadler-proteinatlas/20160525-rawdata/10x images plate 2/plate 2 E7F7 ab 19 MBD4/Sequence/Loop_ 0/A 0_L 0_S 0_U 5_V 7_X 0_Y 0_Job(Seq.Scan) 1 01 01 01_025_z0_ch01.tif
```

```
[omero@test34-omero 27]$ grep TCSReader 13-05-05.613.log | wc
    387   11063  117162
```

**Comment by simleo** [comment]
@joshmoore just pushed https://github.com/openmicroscopy/bioformats/pull/2758/commits/03c2978dab1cc18955f2fcd985fe7098edee543c. With that there should be no `TCSReader` init.

**Comment by joshmoore** [comment]
Merging for importing into demo34

**Pull request merged**
