### PR TITLE
input files for applying annotations in prod44

### PR DESCRIPTION
**Pull request by eleanorwilliams**

### CODE REVIEW

**Comment by eleanorwilliams** [comment]
@joshmoore - this PR is ready for merging for prod44.  Has been tested in test44.

**Comment by sbesson** [comment]
@eleanorwilliams can the idr00035 addition be pushed away as this is not going in prod44? Also should we open https://github.com/IDR/idr-metadata/pull/267/commits/f676d55d2c0e249bad4822c957fea77f74d87001 as a separate PR that we merge immediately to fix Travis across the board?

**Comment by eleanorwilliams** [comment]
@sbesson - ready for review and merging now

**Comment by sbesson** [comment]
See https://github.com/IDR/idr-metadata/pull/266#issuecomment-345653395. Ready to import into the staging server /cc @jburel

**Pull request merged**
