### PR TITLE
idr0023: metadata & bulk import

### PR DESCRIPTION
**Pull request by joshmoore**
Replace: https://github.com/IDR/idr-metadata/pull/89

### CODE REVIEW

**Comment by eleanorwilliams** [comment]
@joshmoore.  What needed to be changed in the bulk import files? Should i change here?

**Comment by eleanorwilliams** [comment]
@joshmoore.  Sorry, I spotted errors in a couple of column headings.  Fixed now.

**Comment by joshmoore** [comment]
@eleanorwilliams : Seh1-aa342-360_antibody_1 has 2 all_particles.tif -- once from 130426_seh1_1 and once from 130426_seh1_2. Suggestion on handling it?

**Comment by eleanorwilliams** [comment]
@joshmoore, its a mess.  My late night fix to dataset names went wrong.   Will take me a while to sort this out.

**Comment by joshmoore** [comment]
Closing in favor of gh-96

**Pull request closed without merging**
