### PR TITLE
Idr0019 addingfiles

### PR DESCRIPTION
**Pull request by eleanorwilliams**
To be tested on mini-IDR before merging.   Note there is deliberately no bulkmap-config.yml file.

### CODE REVIEW

**Comment by joshmoore** [comment]
Did you have a bulkmap.yml for idr0019, @eleanorwilliams ?

**Comment by eleanorwilliams** [comment]
@joshmoore.  See first comment.  There is deliberately no  bulkmap-config.yml.  This is study is like an experiment done in wells but is not a screen as such.  There is no library, and no gene linked to each well.

**Comment by joshmoore** [comment]
Gotcha. Just a heads up that none of the information in annotation.csv will be searchable then.

**Comment by eleanorwilliams** [comment]
@joshmoore.  That's fine.  There really is nothing to search.  Its a bit of a 'stand-alone' study.

**Comment by joshmoore** [comment]
:+1: Merging then. (redness would be fixed with https://github.com/IDR/idr-metadata/pull/95)

**Pull request merged**
