### PR TITLE
Study decoupling

### PR DESCRIPTION
**Pull request by sbesson**
Moves a couple of studies to their own repository managed by @IDR/curators :

- `idr0017` and `idr0019` had been decoupled a few months back to test the scaling of map annotation deletion (see https://github.com/ome/omero-metadata/issues/13)
- `idr0002` and `idr0018` are currently used or candidates for training. Having the study metadata in its own contained repository greatly simplifies the import & annotation process and potential improvements from the training activities /cc @pwalczysko 

As for similar PRs, checking Travis remains green and reviewing `diff -urn` before and after this PR are the main actions.

### CODE REVIEW

**Comment by sbesson** [comment]
Below is the output of `diff -ur ../idr-metadata-orig/ . --exclude='.git'` with and without this PR

```diff
[sbesson@test64-omeroreadwrite idr-metadata]$ diff -ur ../idr-metadata-orig/ . --exclude='.git'
diff -ur '--exclude=.git' ../idr-metadata-orig/.gitmodules ./.gitmodules
--- ../idr-metadata-orig/.gitmodules	2019-05-24 11:27:25.852648745 +0000
+++ ./.gitmodules	2019-05-24 11:23:20.870760284 +0000
@@ -50,3 +50,15 @@
 [submodule "idr0052-walther-condensinmap"]
 	path = idr0052-walther-condensinmap
 	url = git://github.com/IDR/idr0052-walther-condensinmap
+[submodule "idr0002-heriche-condensation"]
+	path = idr0002-heriche-condensation
+	url = git://github.com/IDR/idr0002-heriche-condensation
+[submodule "idr0017-breinig-drugscreen"]
+	path = idr0017-breinig-drugscreen
+	url = git://github.com/IDR/idr0017-breinig-drugscreen
+[submodule "idr0018-neff-histopathology"]
+	path = idr0018-neff-histopathology
+	url = git://github.com/IDR/idr0018-neff-histopathology
+[submodule "idr0019-sero-nfkappab"]
+	path = idr0019-sero-nfkappab
+	url = git://github.com/IDR/idr0019-sero-nfkappab
Only in ./idr0017-breinig-drugscreen: requirements.txt
diff -ur '--exclude=.git' ../idr-metadata-orig/idr0017-breinig-drugscreen/screenA/idr0017-screenA-bulkmap-config.yml ./idr0017-breinig-drugscreen/screenA/idr0017-screenA-bulkmap-config.yml
--- ../idr-metadata-orig/idr0017-breinig-drugscreen/screenA/idr0017-screenA-bulkmap-config.yml	2019-05-24 11:27:32.344778291 +0000
+++ ./idr0017-breinig-drugscreen/screenA/idr0017-screenA-bulkmap-config.yml	2019-05-24 11:23:38.301108096 +0000
@@ -3,21 +3,21 @@
 version: 3
 
 defaults:
-    # Should the column be processed when creating bulk-annotations (yes/no)
-    include: no
-    # Columns type of the bulk-annotations column
-    type: string
-
-    # If non-empty a string used to separate multiple fields in a column
-    # White space will be stripped
-    split:
-    # Should this column be included in the clients (yes/no)
-    includeclient: yes
-    # Should this column be visible in the clients, if no the column should be
-    # hidden in the client but will still be indexed by the searcher (yes/no)
-    visible: yes
-    # Should empty values be omitted from the client display
-    omitempty: yes
+  # Should the column be processed when creating bulk-annotations (yes/no)
+  include: no
+  # Columns type of the bulk-annotations column
+  type: string
+
+  # If non-empty a string used to separate multiple fields in a column
+  # White space will be stripped
+  split:
+  # Should this column be included in the clients (yes/no)
+  includeclient: yes
+  # Should this column be visible in the clients, if no the column should be
+  # hidden in the client but will still be indexed by the searcher (yes/no)
+  visible: yes
+  # Should empty values be omitted from the client display
+  omitempty: yes
 
 columns:
 
@@ -41,69 +41,70 @@
   - group:
       namespace: openmicroscopy.org/mapr/organism
       columns:
-      - name: Characteristics [Organism]
-        clientname: Organism
-        include: yes
+        - name: Characteristics [Organism]
+          clientname: Organism
+          include: yes
 
   - group:
       namespace: openmicroscopy.org/mapr/cell_line
       columns:
-      - name: Characteristics [Cell Line]
-        clientname: Cell Line
-        include: yes
+        - name: Characteristics [Cell Line]
+          clientname: Cell Line
+          include: yes
 
   - group:
       namespace: openmicroscopy.org/mapr/cell_line/supplementary
       columns:
-      - name: Mutation Detailed
-        include: yes
+        - name: Mutation Detailed
+          include: yes
 
   - group:
       namespace: openmicroscopy.org/mapr/compound
       columns:
-      - name: Compound Name
-        include: yes
-      - name: Compound Name
-        clientname: Compound Name URL
-        clientvalue: https://www.ncbi.nlm.nih.gov/pccompound?term={{ value|urlencode }}
-        include: yes
+        - name: Compound Name
+          include: yes
+        - name: Compound Name
+          clientname: Compound Name URL
+          clientvalue: >
+            https://www.ncbi.nlm.nih.gov/pccompound?term={{ value|urlencode }}
+          include: yes
 
   - group:
       namespace: openmicroscopy.org/mapr/compound/supplementary
       columns:
-      - name: Compound Treatment
-        include: yes
-      - name: Compound Secondary Name
-        include: yes
-      - name: Compound Class
-        include: yes
-      - name: Compound Enzyme
-        include: yes
-      - name: Compound Action
-        include: yes
-      - name: Compound Selectivity
-        include: yes
-      - name: Compound Description
-        include: yes
-      - name: Compound Selectivity Updated
-        include: yes
+        - name: Compound Treatment
+          include: yes
+        - name: Compound Secondary Name
+          include: yes
+        - name: Compound Class
+          include: yes
+        - name: Compound Enzyme
+          include: yes
+        - name: Compound Action
+          include: yes
+        - name: Compound Selectivity
+          include: yes
+        - name: Compound Description
+          include: yes
+        - name: Compound Selectivity Updated
+          include: yes
 
 
 # Advanced options (experimental)
 advanced:
-    # If a map-annotation is attached to a well also attach it to all images
-    # in the well
-    well_to_images: yes
-
-    # TODO: Primary key config should be in a global config
-    ignore_missing_primary_key: yes
-    primary_group_keys:
+  # If a map-annotation is attached to a well also attach it to all images
+  # in the well
+  well_to_images: yes
+
+  # TODO: Primary key config should be in a global config
+  ignore_missing_primary_key: yes
+  primary_group_keys:
     - namespace: openmicroscopy.org/mapr/organism
       keys:
-      - Organism
+        - Organism
     - namespace: openmicroscopy.org/mapr/cell_line
       keys:
-      - Cell Line
+        - Cell Line
     - namespace: openmicroscopy.org/mapr/compound
       keys:
-      - Compound Name
+        - Compound Name
diff -ur '--exclude=.git' ../idr-metadata-orig/idr0017-breinig-drugscreen/screenA/idr0017-screenA-bulk.yml ./idr0017-breinig-drugscreen/screenA/idr0017-screenA-bulk.yml
--- ../idr-metadata-orig/idr0017-breinig-drugscreen/screenA/idr0017-screenA-bulk.yml	2019-05-24 11:27:32.344778291 +0000
+++ ./idr0017-breinig-drugscreen/screenA/idr0017-screenA-bulk.yml	2019-05-24 11:23:38.301108096 +0000
@@ -1,4 +1,12 @@
 ---
+continue: "true"
+transfer: "ln_s"
+exclude: "clientpath"
+skip: "all"
+output: "yaml"
+columns:
+    - name
+    - path
+parallel_upload: "50"
 target: "Screen:name:idr0017-breinig-drugscreen/screenA"
-include: "../../bulk.yml"
 path: "idr0017-screenA-plates.tsv"
Only in ./idr0017-breinig-drugscreen: .travis.yml
diff -ur '--exclude=.git' ../idr-metadata-orig/idr0019-sero-nfkappab/screenA/idr0019-screenA-bulk.yml ./idr0019-sero-nfkappab/screenA/idr0019-screenA-bulk.yml
--- ../idr-metadata-orig/idr0019-sero-nfkappab/screenA/idr0019-screenA-bulk.yml	2019-05-24 11:27:32.573782861 +0000
+++ ./idr0019-sero-nfkappab/screenA/idr0019-screenA-bulk.yml	2019-05-24 11:23:40.498151937 +0000
@@ -1,4 +1,12 @@
 ---
+continue: "true"
+transfer: "ln_s"
+exclude: "clientpath"
+checksum_algorithm: "File-Size-64"
+logprefix: "logs/"
+output: "yaml"
+columns:
+    - name
+    - path
 target: "Screen:name:idr0019-sero-nfkappab/screenA"
-include: "../../bulk.yml"
 path: "idr0019-screenA-plates.tsv"
```

As @pwalczysko is starting to work on `idr0018` in the context of the outreach programme, tempted to get this integrated if no objection.

**Comment by joshmoore** [comment]
The only question that has occurred to me so far is whether or not embedded urls on other sites will redirect appropriately.

**Comment by sbesson** [comment]
That's a fair point. Unless they point to a tag, links pointing to decoupled study repositories using the master branch would be broken. Having briefly reviewed public references indexed by Google:

- https://idr.openmicroscopy.org/about/submission.html and similar static pages would need to be adjusted accordingly
- links in email threads like [this one](https://lists.openmicroscopy.org.uk/pipermail/ome-users/2016-October/006228.html) would be broken

**Comment by joshmoore** [comment]
Thanks for the fixes. Happy to ignore the email problem. Someone actually going to the UI should be able to figure it out in the future. :+1:

**Pull request merged**
