### PR TITLE
Study parser utility

### PR DESCRIPTION
**Pull request by sbesson**
This PR creates a utility class to parse the content of the version 1 of IDR study files (INI file based).

- for each study file, the mandatory and optional fields are read depending on the study type (experiment vs screen). Errors are thrown on missing mandatory fields
- the metadata block for each study component (experiment, screen) is detected and parsed
- the publications are turned into a list with `Title` and `Authors` as the mandatory fields and `Preprint`, `DOI`, `PMCID`, `PubMed ID` as the optional fields.
- some validation is performed on some fields
- a class is created to generate the attribute of OMERO objects corresponding to the study/experiments/screens (description, name, map annotation key/value pairs)

## Testing

- run `python pyidr/study_parser.py <idrXXX-YYY-ZZZ>/<idrXXX-study.txt>`. This should throw an exception if some invalidities are found
- run `python pyidr/study_parser.py <idrXXX-YYY-ZZZ>/<idrXXX-study.txt> --report`. This should turn the parsed content into fields matching what is on OMERO
- review the output of Travis which should run the parser in non-failing mode

## Next steps

- update the various studies failing the parsing 
- update the script logic and Travis to fail on invalid study metadata
- consume the object classes to assert the correctness of the annotations on IDR (e.g. `python pyidr/study_parser.py --check`)

/cc @pwalczysko @dominikl

### CODE REVIEW

**Comment by dominikl** [comment]
👍  Looks good. Definitely helpful in spotting errors in the study file, just used it to fix the idr0040 study.txt :-) https://github.com/IDR/idr0040-aymoz-singlecell/pull/2/commits/95f6ebb0e5255db07973ee3747ff212019141114

**Comment by sbesson** [comment]
Thanks @dominikl. Two general additions:

- we might need to discuss where this should live i.e. is it time to start migrating our tools to handle IDR metadata and formats to`idr-py`?
- @manics pointed out his https://github.com/IDR/idr-metadata/compare/master...manics:study-to-mapann branch which contains lots of complementary content. I will have a look at what can be unified/reused

**Comment by pwalczysko** [comment]
How is STUDY_KEY defined as opposed to COMPONENT_KEY please ?
Maybe it could be that the STUDY_KEYs are the ones which have the word "Study..." at the beginning.
But where does the "Term Source Name" which is under the "Study contacts" paragraph belong then ?

**Comment by pwalczysko** [comment]
```
python pyidr/study_parser.py ~/Work/idr0041-cai-mitoticatlas/idr0041-study.txt 
INFO:root:Reading /Users/pwalczysko/Work/idr0041-cai-mitoticatlas/idr0041-study.txt
[pwalczysko@ls31619 ~/Work/idr-metadata]$ 
```

Not sure what to conclude from the above ? Does the script say "all okay" ? Did the script change the study file to be okay somehow ?

**Comment by sbesson** [comment]
Answering the 2 comments above:

- component means screen or experiment. In the IDR semantics, 1 study is constituted of n Experiments of Studies. The study keys are  unique but the experiment/screen keys are duplicated for each iteration.
- not all keys of the file are parsed at the moment, only the one used for populating the OMERO Project/Screens are considered
- right now the script will only be verbose if there is an error during the parsing, I can certainly added a "Parsed without errors" message to clarify

**Comment by pwalczysko** [comment]
Two workflows tried

1. Delete the "Study title" completely, Key and Value, output see below (seems like a python error rather than a warning ?)
2. Delete just the Value of the "Study title" Key, output see below -> where is my warning ?

1.
```
[pwalczysko@ls31619 ~/Work/idr-metadata]$ python pyidr/study_parser.py ~/Work/idr0041-cai-mitoticatlas/idr0041-study.txt 
INFO:root:Reading /Users/pwalczysko/Work/idr0041-cai-mitoticatlas/idr0041-study.txt
Traceback (most recent call last):
  File "pyidr/study_parser.py", line 106, in <module>
    parser = StudyParser(f.readlines())
  File "pyidr/study_parser.py", line 40, in __init__
    self.parse_study()
  File "pyidr/study_parser.py", line 57, in parse_study
    self.study[key1] = self.get_value(key2)
  File "pyidr/study_parser.py", line 52, in get_value
    raise Exception("Could not find value for key %s " % key)
Exception: Could not find value for key Study Title 
```
2.
```
[pwalczysko@ls31619 ~/Work/idr-metadata]$ python pyidr/study_parser.py ~/Work/idr0041-cai-mitoticatlas/idr0041-study.txt 
INFO:root:Reading /Users/pwalczysko/Work/idr0041-cai-mitoticatlas/idr0041-study.txt
[pwalczysko@ls31619 ~/Work/idr-metadata]$ python pyidr/study_parser.py ~/Work/idr0041-cai-mitoticatlas/idr0041-study.txt 
INFO:root:Reading /Users/pwalczysko/Work/idr0041-cai-mitoticatlas/idr0041-study.txt
[pwalczysko@ls31619 ~/Work/idr-metadata]$ 
```

**Comment by pwalczysko** [comment]
>"Parsed without errors" message to clarify

Rather, parsed and found this and that as a message (without errors is very vague, if you are  not completely familiar with study files, you struggle with understanding what the script is actually checking, see https://github.com/IDR/idr-metadata/pull/304#issuecomment-376928787)

**Comment by dominikl** [comment]
Very useful tool. Good to merge from my point of view 👍 Guess @pwalczysko will want to give it another test, too.

**Comment by sbesson** [comment]
Discussed briefly. Merging this as per https://github.com/IDR/idr-metadata/pull/304#issuecomment-381927337 so that we can make progress on the study validation cleanup. @pwalczysko can review it when he finds the time.

**Pull request merged**
