### PR TITLE
idr0021

### PR DESCRIPTION
**Pull request by eleanorwilliams**
Annotations ready for testing

### CODE REVIEW

**Comment by joshmoore** [comment]
This change was needed:

```
[omero@minke experimentA]$ git diff ../../idr0021-lawo-pericentriolarmaterial/experimentA/idr0021-experimentA-bulkmap-config.yml
diff --git a/idr0021-lawo-pericentriolarmaterial/experimentA/idr0021-experimentA-bulkmap-config.yml b/idr0021-lawo-pericentriolarmaterial/experimentA/idr0021-experimentA-bulkmap-config.yml
index e879944..5a330dd 100644
--- a/idr0021-lawo-pericentriolarmaterial/experimentA/idr0021-experimentA-bulkmap-config.yml
+++ b/idr0021-lawo-pericentriolarmaterial/experimentA/idr0021-experimentA-bulkmap-config.yml
@@ -41,9 +41,9 @@ columns:
     include: yes
   - name: Phenotype 1 Term Name
     include: yes
-  - name: Phenotype 1 Term Accession
+  - name: Phenotype1TermAccession
     include: yes
-  - name: Phenotype 1 Term Accession
+  - name: Phenotype1TermAccession
     clientname: Phenotype 1 Term Accession URL
     clientvalue: http://www.ebi.ac.uk/cmpo/{{ value }}
     include: yes
```

**Comment by eleanorwilliams** [comment]
@joshmoore.  Rather than changing 'Phenotype 1 Term Accession' -> 'Phenotype1TermAccession' in bulkmap-config.yml I have fixed it the opposite way round in annotation.csv so that the column heading has spaces. 

As a separate issue I noticed a missing colon in the link to PDBe in the bulkmap-config.yml file.

If the bulk annotation has already been loaded this means that is will need to be reloaded. Sorry!

**Comment by eleanorwilliams** [comment]
Don't test load yet, will need to fix dataset names to take into account the two CEP120 datasets we now have.

**Comment by eleanorwilliams** [comment]
Ok, ready for testing. I had already fixed this in the annotation.csv file and filePaths.tsv.  Just had to fix assays.txt.

**Comment by joshmoore** [comment]
```
INFO:omero.util.populate_metadata:Created 414 MapAnnotations
```

**Pull request merged**
