### PR TITLE
Fix cellmorph .screen files

### PR DESCRIPTION
**Pull request by simleo**
Three main items:

 * Add `AxisTypes` and `ChannelNames` entries according to https://github.com/openmicroscopy/bioformats/pull/2389. This (only the former, actually, while the latter just sets names for the channels) fixes a problem where some images were being incorrectly interpreted as Z-stacks.
 * Skip wells with empty TIFF files in the secondary screens. This is an attempt to fix Bio-Formats crashing on empty files. However, a test showed that this is not enough in practice: those files have a "MATROX Imaging Library" software TIFF tag, so B-F reads them with BDReader, which explores the tree in search for auxiliary files and eventually finds the empty ones even though they are not listed in the .screen file. It should still be useful to fix the .screen files in this way. In the future, we might change B-F's behavior so that it does not try to auto-detect a layout when it's already being provided by the top-level format as is the case here.
 * Take into account a few exceptions where file names have a leading tilde in the primary screen

### CODE REVIEW

**Comment by simleo** [comment]
Travis found a problem, looking at it now.

**Comment by simleo** [comment]
After excluding wells with empty files, `UR301-1.screen` was left with 0 file entries, and `check_screen.py` wasn't prepared for that.

@joshmoore should we remove UR301-1.screen altogether?

**Comment by joshmoore** [comment]
If it has no images, yes. Just need to check with @eleanorwilliams, if that matches expectations.

**Comment by eleanorwilliams** [comment]
@simleo @joshmoore Plate UR301-1 is not part of screenC.  The plates for screen C are
UR301-3
UR301-4
UR302-3
UR302-4
UR303-3
UR303-4

**Comment by simleo** [comment]
OK, I'll remove it in a future commit. Looks like I also have to fix 10 `.screen`s from primary, see the Trello card.

**Comment by joshmoore** [comment]
Is the next step here to attempt re-imports?

**Comment by simleo** [comment]
@joshmoore I think so. `screenA` should go in fine now, except for `HT47` which hasn't changed because it seems to have no problems as far as `check_screen` can tell (see card).

**Comment by joshmoore** [comment]
Merging. My planned steps are:

 * checkout to EBI production and attempt loading one of the existing cellmorphs to see if there are any issues caused by the changes.
   * if yes, revert screenA and focus on screenB & C
   * if no, import the missing screenA plates
 * import screenB & screenC

**Pull request merged**
