### PR TITLE
Idr0021 PDBe links

### PR DESCRIPTION
**Pull request by eleanorwilliams**
@joshmoore  PDBe links now should work.

### CODE REVIEW

**Comment by joshmoore** [comment]
This has a mix of commits. Did you only want the last 2?

**Comment by eleanorwilliams** [comment]
OMG what have I done!  No I only want the last one for idr0021

**Comment by joshmoore** [comment]
Trying to apply the last commit with:

```
 1070  git cherry-pick --strategy=recursive -X theirs a41d8b7b92544b74af0e4b098ce197d31209eb4f
```

**Comment by joshmoore** [comment]
```
KeyError: 'all_particles.tif'
```

**Comment by eleanorwilliams** [comment]
Tested in production idr-demo and links to PDBe now work.

**Comment by joshmoore** [comment]
Migrating to its own PR:

```
/opt/idr-metadata $ git rebase --onto origin/master --strategy=recursive -X theirs HEAD^
First, rewinding head to replay your work on top of it...
Auto-merging idr0021-lawo-pericentriolarmaterial/experimentA/idr0021-experimentA-bulkmap-config.yml
Auto-merging idr0021-lawo-pericentriolarmaterial/experimentA/idr0021-experimentA-assays.txt
Auto-merging idr0021-lawo-pericentriolarmaterial/experimentA/idr0021-experimentA-annotation.csv
[detached HEAD 354dd1a] fixed link to PDBe in bulkmap. Also added column "Antibody Target" to assay, annotation and bulkmap file and changed values in "Targeted Protein" column to be just the protein name so PDBe links based on this column will all work
 Author: eleanorwilliams <e.x.williams@dundee.ac.uk>
 Date: Wed May 25 12:46:21 2016 +0100
 3 files changed, 832 insertions(+), 830 deletions(-)
 rewrite idr0021-lawo-pericentriolarmaterial/experimentA/idr0021-experimentA-annotation.csv (71%)
Committed: 0001 fixed link to PDBe in bulkmap. Also added column "Antibody Target" to assay, annotation and bulkmap file and changed values in "Targeted Protein" column to be just the protein name so PDBe links based on this column will all work
All done.

```

**Pull request closed without merging**
